apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  labels:
    app: wluox
  name: wluox
spec:
  replicas: 9
  selector:
    matchLabels:
      app: wluox
  template:
    metadata:
      labels:
        app: wluox
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        env:
          - name: NETTOOL_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - zone2
                - zone3
            topologyKey: topology.kubernetes.io/zone

          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - wluox
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: wluo
spec:
  type: NodePort
  selector:
    app: wluox
  ports:
  - name: wluo
    port: 80
    targetPort: 80
    nodePort: 32000
