---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: default
spec:
  ca:
    secretName: ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-cert
  namespace: default
  labels:
    app: bookinfo.cilium.rocks
spec:
  secretName: demo-cert
  duration: 8760h
  issuerRef:
    name: my-ca-issuer
  commonName: "bookinfo.cilium.rocks"
  dnsNames:
  - bookinfo.cilium.rocks

