apiVersion: apps/v1
kind: Deployment
metadata:
  name: wluox
spec:
  replicas: 9
  selector:
    matchLabels:
      app: wluox
  template:
    metadata:
      labels:
        app: wluox
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - wluox
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - zone1
                - zone2
      containers:
      - name: nettoolbox
        image: 192.168.2.100:5000/nettool
        env:
        - name: NETTOOL_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
