---
# Source: provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-pv-provisioner-config
  namespace: default
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv
data:
  storageClassMap: |
    localpv-sc:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"

---
# Source: provisioner/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: localpv
  namespace: default
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv

---
# Source: provisioner/templates/rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-pv-provisioner-pv-binding
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv
subjects:
- kind: ServiceAccount
  name: localpv
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-pv-provisioner-node-clusterrole
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-pv-provisioner-node-binding
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv
subjects:
- kind: ServiceAccount
  name: localpv
  namespace: default
roleRef:
  kind: ClusterRole
  name: local-pv-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
# Source: provisioner/templates/daemonset.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-pv-provisioner
  namespace: default
  labels:
    helm.sh/chart: provisioner-2.4.0
    app.kubernetes.io/name: provisioner
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: local-pv
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: provisioner
      app.kubernetes.io/instance: local-pv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: provisioner
        app.kubernetes.io/instance: local-pv
      annotations:
        checksum/config: eccb3937d2c65e7e2c537d0f114a58b99b55b3c220ed251d9a4c5c858f2a3ad3
    spec:
      serviceAccountName: localpv
      containers:
        - name: provisioner
          image: quay.io/external_storage/local-volume-provisioner:v2.4.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: quay.io/external_storage/local-volume-provisioner:v2.4.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: localpv-sc
              mountPath: /mnt/disks
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: local-pv-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: localpv-sc
          hostPath:
            path: /mnt/disks

---
# Source: provisioner/templates/psp.yaml


---
# Source: provisioner/templates/servicemonitor.yaml


---
# Source: provisioner/templates/storageclass.yaml


