---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: frontend
  name: frontend
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: frontend
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    role: backend
  name: backend
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: backend
