apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.cilium.io/mac-address: e2:9c:30:38:52:61
  labels:
    app: wluo
  name: wluo
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: cni
