apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  labels:
    app: wluo
  name: wluo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      # 1.Share IPC 
      #hostIPC: true
      # 2.Share host Network
      #hostNetwork: true
      # 3.Inherit the process ID from the host
      #hostPID: true
      volumes:
      - name: host
        hostPath:
          path: /
          type: Directory
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        volumeMounts:
        - name: host
          mountPath: /host
        env:
          - name: NETTOOL_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: wluo
spec:
  type: NodePort
  selector:
    app: wluo
  ports:
  - name: wluo
    port: 80
    targetPort: 80
    nodePort: 32000
