apiVersion: v1
kind: Pod
metadata:
  name: vpp
  #annotations:
  #  k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  containers:
  - name: vpp
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: hugepage
      mountPath: /hugepages
    command: [ "/sbin/init" ]
    #command: [ "/bin/bash", "-c", "--" ]
    #args: [ "while true; do sleep 300000; done;" ]
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 4
        memory: 2G
        hugepages-1Gi: 2Gi
        intel.com/sriov_vppdpdk5: '1'
        intel.com/sriov_vppdpdk8: '1'
      limits:
        cpu: 4
        memory: 2G
        hugepages-1Gi: 2Gi
        intel.com/sriov_vppdpdk5: '1'
        intel.com/sriov_vppdpdk8: '1'
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
