apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-api
  name: sample-api-server
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      restartPolicy: Always
      volumes:
      - name: tls
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
             csi.cert-manager.io/issuer-name: my-ca-issuer
             csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}.svc.cluster.local,sample-api-service.sandbox.svc.cluster.local,sample-api-service.sandbox.svc.,sample-api-service.
      containers:
      - name: sample-api
        image: 192.168.2.100:5000/k9t3d5o9/secureservice:latest
        volumeMounts:
        - mountPath: "/etc/tls"
          name: tls
          readOnly: true
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-api-service
  name: sample-api-service
  namespace: sandbox
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: sample-api
  type: ClusterIP
