apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wluo
  name: wluo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      nodeName: cilium-kpr-ebpf-ext-traffic-policy-worker
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        env:
          - name: NETTOOL_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: wluo
spec:
  # externalTrafficPolicy: Cluster
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: wluo
  ports:
  - name: wluo
    port: 80
    targetPort: 80
    nodePort: 32000
