apiVersion: v1
name: cni
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
appVersion: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82
description: Helm chart for istio-cni components
keywords:
  - istio-cni
  - istio
sources:
  - http://github.com/istio/cni
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
