apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "wluo"
spec:
  cidrs:
  - cidr: "12.1.5.0/24"
  serviceSelector:
    matchLabels:
      app: wluo
---


apiVersion: v1
kind: Service
metadata:
  name: wluo
  labels:
    app: wluo
spec:
  type: LoadBalancer
  selector:
    app: wluo
  ports:
  - port: 80
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wluo
  name: wluo
spec:
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true
