apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wluo
  name: wluo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        env:
          - name: NETTOOL_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NETTOOL_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 80
          hostPort: 12345
        securityContext:
          privileged: true
