apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 172.18.0.200-172.18.0.210
