apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  labels:
    app: wluo
  name: wluo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      hostNetwork: true
      hostUsers: false
      volumes:
      - name: host
        hostPath:
          path: /proc
          type: Directory
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        volumeMounts:
        - name: host
          mountPath: /proc
        env:
          - name: NETTOOL_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          procMount: Default
          
---
apiVersion: v1
kind: Service
metadata:
  name: wluo
spec:
  type: NodePort
  selector:
    app: wluo
  ports:
  - name: wluo
    port: 80
    targetPort: 80
    nodePort: 32000
