apiVersion: v1
kind: Pod
metadata:
  name: shm
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    name: nettoolbox
    imagePullPolicy: "IfNotPresent"
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /dev/shm
        name: shm
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 128Mi
    name: shm
