apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "wluo"
spec:
  blocks:
  #- cidr: "172.18.0.0/24"
  - start: "172.18.0.201"
    stop: "172.18.0.205"
  serviceSelector:
    matchLabels:
      app: wluo
---
apiVersion: v1
kind: Service
metadata:
  name: service-lb-ipam
  labels:
    app: wluo
spec:
  type: LoadBalancer
  selector:
    app: wluo
  ports:
  - port: 80
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wluo
  name: lb-ipam
spec:
  selector:
    matchLabels:
      app: wluo
  template:
    metadata:
      labels:
        app: wluo
    spec:
      containers:
      - image: 192.168.2.100:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true
