---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-ca-issuer
  namespace: default
spec:
  ca:
    secretName: root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: assgin-ca-request-tls
  namespace: default
  labels:
    app: www-example-com
spec:
  secretName: default-ns-https-example.foo.com
  duration: 8760h
  issuerRef:
    name: my-ca-issuer
  commonName: "default-ns-https-example.foo.com"
  dnsNames:
  - default-ns-https-example.foo.com

